name: Run Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage

      - name: Run Unit Tests with Coverage
        env:
          PYTHONPATH: ./src:.
        run: |
          coverage run --source=src tests/unitTests/all_tests.py

      - name: Upload coverage data
        uses: actions/upload-artifact@v4
        with:
          name: raw-coverage
          path: .coverage
